INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Nigeria','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Egypt','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Ethiopia','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Democratic Republic of the Congo','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('South Africa','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Tanzania','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Kenya','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Algeria','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Sudan','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Uganda','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Morocco','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Ghana','1');INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Angola','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Mozambique','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Côte d’Ivoire','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Madagascar','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Cameroon','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Niger','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Burkina Faso','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Mali','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Malawi','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Zambia','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Senegal','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Chad','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Somalia','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Zimbabwe','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('South Sudan','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Rwanda','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Guinea','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Benin','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Tunisia','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Burundi','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Sierra Leone','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Togo','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Libya','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Central African Republic','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Republic of the Congo','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Liberia','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Mauritania','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Eritrea','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Namibia','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Gambia','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Botswana','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Gabon','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Lesotho','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Guinea-Bissau','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Swaziland','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Equatorial Guinea','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Mauritius','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Djibouti','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Comoros','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Cape Verde','1');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Sao Tome and Principe','2');
INSERT INTO `countries`(`country_name`,`region_id`) VALUES ('Seychelles','2');

